server:
  port: 9090

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    # org.springframework.boot.autoconfigure.security.oauth2.OAuth2ClientProperties
    client:
      client-id: clientapp
      client-secret: 123456
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    # org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerProperties
    resource:
      token-info-uri: http://127.0.0.1:8080/oauth/check_token # 获得 Token 信息的 URL
    # 访问令牌获取 URL，自定义的用于实现自定义登陆接口
    access-token-uri: http://127.0.0.1:8080/oauth/token
